# Rust formatting configuration for QAuth
# https://rust-lang.github.io/rustfmt/

edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Auto"

# Imports
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_imports = true

# Comments
wrap_comments = true
comment_width = 100
normalize_comments = true

# Functions
fn_params_layout = "Tall"
fn_single_line = false

# Structs
struct_lit_single_line = true
struct_variant_width = 35

# Control flow
match_block_trailing_comma = true
match_arm_leading_pipes = "Never"

# Macros
format_macro_matchers = true
format_macro_bodies = true

# Other
use_small_heuristics = "Default"
format_code_in_doc_comments = true
doc_comment_code_block_width = 80
